---
  - hosts: database
    become: true
    remote_user: ubuntu
    tasks:
      - name: install mysql/tools & ensure running
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - mysql-server
          - python-mysqldb

      - name: ensure that mysql is running
        service: name=mysql state=started enabled=yes

      - name: ensure that mysql is listening on all ports
        lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
                    line="bind-address = 0.0.0.0"
        notify: restart mysql

      - name: create demo database
        mysql_db: name=demo state=present

      - name: create demo user
        mysql_user: name=demo password=demo priv='demo.*:ALL' host='%' state=present


    handlers:
      - name: restart mysql
        service: name=mysql state=restarted
