---

#Brings stack down starting with front end to reduce database write problems.
  - hosts: loadbalancer
    become: true
    remote_user: ubuntu
    tasks:
    - service: name=nginx state=restarted

  - hosts: web
    become: true
    remote_user: ubuntu
    tasks:
    - service: name=apache2 state=stopped

#Restart mysql
  - hosts: database
    become: true
    remote_user: ubuntu
    tasks:
    - service: name=mysql state=restarted

#Bring stack up in reverse order
  - hosts: web
    become: true
    remote_user: ubuntu
    tasks:
    - service: name=apache2 state=started

  - hosts: loadbalancer
    become: true
    remote_user: ubuntu
    tasks:
    - service: name=nginx state=restarted
