---
#purpose of this document is to barely touch the production enviornment
#only gives you the status of the services that are required for the stack to run
 - hosts: loadbalancer
   become: true
   remote_user: ubuntu
   tasks:
     - name: verify nginx service
       command: service nginx status

 - hosts: web
   become: true
   remote_user: ubuntu
   tasks:
     - name: verify apache2 service
       command: service apache2 status

 - hosts: database
   become: true
   remote_user: ubuntu

   tasks:
     - name: verify mysql service
       command: service mysql status
